config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "welcome/index"

  get    "/login",    to: "sessions#new"
  post   "/login",    to: "sessions#create"
  get    "/logout",   to: "sessions#destroy"

  namespace :admin do
    resources :stations
    resources :preview_stations, only: :new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log_entry.rb
# == Schema Information
#
# Table name: log_entries
#
#  id         :bigint(8)        not null, primary key
#  artist     :string           not null
#  title      :string           not null
#  slug       :string           not null
#  station_id :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_log_entries_on_slug        (slug)
#  index_log_entries_on_station_id  (station_id)
#
# Foreign Keys
#
#  fk_rails_...  (station_id => stations.id)
#

class LogEntry < ApplicationRecord
  belongs_to :station

  def self.recent
    limit(20).order(id: :desc)
  end
end

app/models/station.rb
# == Schema Information
#
# Table name: stations
#
#  id             :bigint(8)        not null, primary key
#  name           :string           not null
#  url            :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  scraper        :string
#  artist_script  :string
#  title_script   :string
#  last_logged_at :datetime
#  disabled       :boolean
#
# Indexes
#
#  index_stations_on_name  (name) UNIQUE
#

class Station < ApplicationRecord
  SCRAPERS = %i[css]

  has_many :log_entries, dependent: :destroy
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_secure_password
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authorize

  protected

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/admin/preview_stations_controller.rb
class Admin::PreviewStationsController < Admin::BaseController
  def new
    preview = Admin::PreviewForm.new(preview_params)
    preview.call
    @preview = Admin::PreviewPresenter.new(preview)
  end

  private

  def preview_params
    params.permit(:name, :url, :scraper, :artist_script, :title_script)
  end
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < Admin::BaseController
  before_action :redirect_preview, only: %i[create update]
  def index
    @stations = Admin::StationPresenter.wrap(Station.all)
  end

  def new
    @station_form = Admin::StationForm.new
  end

  def create
    @station_form = Admin::StationForm.new(station_params)
    if @station_form.call
      redirect_to admin_stations_path, notice: "Station created"
    else
      render :new
    end
  end

  def edit
    station = ::Station.find params[:id]
    @station_form = Admin::StationForm.new(station.attributes.slice(*station_attibutes))
  end

  def update
    @station_form = Admin::StationForm.new(station_params.merge(id: params[:id]))
    if @station_form.call
      redirect_to admin_stations_path, notice: "Station updated"
    else
      render :edit
    end
  end

  def destroy
    station = ::Station.find params[:id]
    station.destroy

    redirect_to admin_stations_path, notice: "Station #{station.name} deleted"
  end

  private

  def redirect_preview
    redirect_to new_admin_preview_station_path(station_params) if params[:preview]
  end

  def station_attibutes
    Admin::StationForm::ATTRIBUTES
  end

  def station_params
    params.require(:station).permit(station_attibutes - ["id"])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  protected

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    login_user = LoginUser.new(session_params)
    if login_user.call
      session[:user_id] = login_user.user_id
      redirect_to root_path, notice: "You are successfully logged in!"
    else
      redirect_to login_path, alert: "email or password doesn't fit!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    log_entries = LogEntry.recent
    @log_entries = LogEntryPresenter.wrap log_entries
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # date/time
  def format_time(time)
    time&.strftime "%H:%M"
  end

  def format_date(date)
    date&.strftime "%d.%m.%Y"
  end

  def format_datetime(date)
    date&.strftime "%d.%m.%Y %H:%M"
  end

  # buttons
  def icon_tag(icon, options = {})
    html_class = "fa fa-#{icon} " + options[:class].to_s
    content_tag(:i, "&nbsp;".html_safe, class: html_class) # rubocop:disable Rails/OutputSafety
  end

  def button_with_icon(link, text, icon, options = {})
    options.reverse_merge! class: "btn btn-default"
    link_to icon_tag(icon) + text, link, options
  end

  def show_button(link, text = "Show", options = {})
    options.reverse_merge! class: "btn btn-info"
    button_with_icon link, text, "link", options
  end

  def add_button(link, text = "Add", options = {})
    options.reverse_merge! class: "btn btn-primary add-button"
    button_with_icon link, text, "plus", options
  end

  def edit_button(link, text = "Edit", options = {})
    link = link.is_a?(ActiveRecord::Base) ? [:edit, link] : link
    options.reverse_merge! class: "btn btn-primary"
    button_with_icon link, text, "pencil", options
  end

  def submit_button(text = "Save", options = {})
    options.reverse_merge! class: "btn btn-success", type: "submit"
    button_tag options do
      icon_tag(:check) + safe_join([text])
    end
  end

  def remove_button(link, text = "Remove", options = {})
    options.reverse_merge! data: {confirm: "Are you sure?"}, class: "btn btn-danger"
    button_with_icon link, text, "trash", options
  end

  def delete_button(link, text = "Delete", options = {})
    options.reverse_merge! data: {confirm: "Are you sure?"},
                           method: :delete, class: "btn btn-danger"
    button_with_icon link, text, "trash", options
  end

  def back_button(link = :back, text = "Back", options = {})
    options.reverse_merge! class: "btn btn-default"
    button_with_icon link, text, "arrow-left", options
  end

  def cancel_button(link = :back, text = "Cancel", options = {})
    options.reverse_merge! class: "btn btn-danger"
    button_with_icon link, text, "remove", options
  end

  def show_boolean_value(value)
    if value
      icon_tag :check, class: "text-success"
    else
      icon_tag :times, class: "text-danger"
    end
  end
end

app/views/admin/preview_stations/new.html.haml
%h1= "Preview for #{@preview.name}"

.well= link_to @preview.url, @preview.url

#preview
  .panel-body
    %dl.clearfix
      %dt.col-lg-2 Artist
      %dd.col-lg-10= @preview.track.artist
      %dt.col-lg-2 Title
      %dd.col-lg-10= @preview.track.title

app/views/admin/stations/_form.html.haml
= form_for [:admin, @station_form], :html => { :class => "form-horizontal" } do |f|
  = render "layouts/errors", object: f.object
  .form-group
    = f.label :name, :class => "control-label"
    = f.text_field :name, :class => "text-field form-control", :required => true
  .form-group
    = f.label :url
    = f.text_field :url, :class => "text-field form-control", :required => true
  .form-group
    = f.label :scraper
    = f.select :scraper, ::Station::SCRAPERS, :class => "text-field form-control", :required => true
  .form-group
    = f.label :title_script
    = f.text_field :title_script, :class => "text-field form-control", :required => true
  .form-group
    = f.label :artist_script
    = f.text_field :artist_script, :class => "text-field form-control", :required => true
  .form-group
    = f.label :disabled
    = f.check_box :disabled, :class => "checkboxform-control", :required => false
  = submit_button "Save"
  = submit_button "Preview", id: :preview, name: "preview"

app/views/admin/stations/edit.html.haml
%h1 Update station

= render "form"

app/views/admin/stations/index.html.haml
%h1 Stations

.row
  .col-md-12
    %table.table.table-sm.table-condensed.table-hover
      %thead
        %tr
          %th Name
          %th Last logged
          %th
      %tbody
        - @stations.each do |station|
          %tr{id: "station_#{station.id}", class: "#{'warning' if station.disabled?}"}
            %td= station.name
            %td= format_datetime station.last_logged_at
            %td
              = edit_button edit_admin_station_path(station)
              = delete_button admin_station_path(station)

    = add_button new_admin_station_url, "New"

app/views/admin/stations/new.html.haml
%h1 New station

= render "form"

app/views/layouts/_errors.html.haml
- if object.errors.any?
  .alert.alert-error
    %a.close{"data-dismiss" => "alert"} ×
    %ul
      - object.errors.full_messages.each do |msg|
        = content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Home"
    %meta{:content => "#{content_for?(:description) ? yield(:description) : "no description"}", :name => "description"}/
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %nav.navbar.navbar-default{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar

          = link_to "Home", root_path, class: "navbar-brand"
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            - if current_user
              %li= link_to "Stations", admin_stations_path, class: "active"
              %li= link_to "Logout", logout_path, class: "active"
            - else
              %li= link_to "Login", login_path, class: "active"
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              - flash.each do |name, msg|
                - if msg.is_a?(String)
                  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
                    %a.close{"data-dismiss" => "alert"} ×
                    = content_tag :div, msg, :id => "flash_#{name}"
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/welcome/index.html.haml
%h1 Welcome to Radio Logger

%p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.


%h2 Last Tracks

#tracks
  %table.table.table-sm.table-condensed.table-hover
    %thead
      %tr
        %th Date
        %th Artist
        %th Title
        %th Station
    %tbody
      - @log_entries.each do |entry|
        %tr{id: "entry_#{entry.id}"}
          %td= format_datetime entry.created_at
          %td= entry.artist
          %td= entry.title
          %td= link_to entry.station_name, edit_admin_station_path(entry.station)